name: Publish
on:
  push:
    branches:
      - 'release-*'
jobs:
  publish:
    name: 'Publish for all platforms'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependecies
        run: npm install
      - name: build
        run: npm run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.{zip,tar}
          draft: true
          file_glob: true
          tag: ${{ github.ref }}
