name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: 'Build for all platforms'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependecies
        run: npm install
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/morpheus-*
  publish:
    name: 'Release for all platforms'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/morpheus-*
          draft: true
          file_glob: true
          tag: ${{ github.ref }}
